//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdminler
    {
        public byte AdminID { get; set; }
        public string KullaniciIsim { get; set; }
        public string KullaniciSifre { get; set; }
    }
}
